# Generated by Django 4.2.6 on 2023-11-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oder',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='oder',
            name='total_diamond',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='player_id',
            field=models.IntegerField(),
        ),
    ]
