# Generated by Django 4.2.6 on 2023-11-14 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_oder_price_alter_oder_total_diamond_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_diamond', models.IntegerField()),
                ('price', models.IntegerField()),
                ('payment_method', models.CharField(default='DANA', max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Oder',
        ),
    ]
