# Generated by Django 4.2.6 on 2023-12-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
